[jjbb] filter only for the default branch, PRs and tags
elastic/apm-agent-java pull request #2389
Opened 2022-01-11 11:25 UTC by v1v

## What does this PR do?

Filter the main pipeline with:
- the default branch -> master
- PRs
- tags with the format `vd.d.d.*` -> therefore v1.0.0 and v1.0.1-RC1 are supported 

Therefore `1.x` and `1.26` won't be in the list of branches to be built in the CI

## Test

![image](https://user-images.githubusercontent.com/2871786/148934272-bf5564b3-8029-42f7-b0ba-ee940928635b.png)

![image](https://user-images.githubusercontent.com/2871786/148934306-0d1b2c02-03e5-4dde-9d66-102495b2225d.png)

![image](https://user-images.githubusercontent.com/2871786/148934327-79fa8ddc-cd57-4602-bc2c-11be3e4ad2a2.png)

2022-01-11 12:34 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2389/detail/PR-2389/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2389/detail/PR-2389/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2389/detail/PR-2389/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2389/detail/PR-2389/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-java_2389.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-01-11T11:15:48.907Z&rangeTo=2022-01-11T11:35:48.907Z&transactionName=apm-agent-java%2Fapm-agent-java-mbp%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=4590a9b0ce2bf12d322cc6feaf5ea821&transactionId=881b1060e3ff7bb3)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-01-11T11:25:48.907+0000


* Duration: 69 min 46 sec


* Commit: 8af8d47739bcdcccfbd264bd43397c98c3af1eb8



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2640  |
| Skipped      | 21 |
| Total        | 2661   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run benchmark tests` : Run the benchmark test.


- `run compatibility tests` : Run the JDK Compatibility test.


- `run integration tests` : Run the APM-ITs.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-01-11 14:20 UTC, kuisathaverat approved these changes

2022-01-13 08:21 UTC, SylvainJuge commented
Thanks for this.

Is there any value to keep building existing tags ?
- they are (or should be) immutable, thus there is no need to rebuild them once the release is done
- when doing the release, it means an extra execution will be triggered when the tag is created, which just duplicates the work done by the release job that is creating the release artifact.

Of course, it would be different if our "main build pipeline" would automatically create release artifacts when executed on a tag, but it's not the case currently.

2022-01-17 18:16 UTC, v1v commented
> Is there any value to keep building existing tags ?

No strong opinion, this PR was intended to fulfil the initial requirement. So I'd say the one regarding whether to listen from tags in the main pipeline versus those tags were already verified in the release pipeline could be done in a follow up. 

What do you think?

2022-01-18 10:15 UTC, SylvainJuge requested changes
We really don't have any use for re-building tags here, and the change seems quite minimal, thus let's remove them.

2022-01-18 10:15 UTC, SylvainJuge commented on .ci/jobs/apm-agent-java-mbp.yml
> +            head-filter-regex: '(master|PR-.*|v\d+\.\d+\.\d+.*)'
```suggestion
            head-filter-regex: '(master|PR-.*)'
```

2022-01-18 10:53 UTC, SylvainJuge approved these changes

2022-01-18 13:38 UTC, merged