document the metric_set_limit option
elastic/apm-agent-java pull request #2717
Opened 2022-07-19 16:15 UTC by jackshirazi

## What does this PR do?
document the metric_set_limit option per comments in https://github.com/elastic/apm-agent-java/pull/2148 - making the option not `internal` and expand the documentation

2022-07-19 16:47 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2717/detail/PR-2717/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2717/detail/PR-2717/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2717/detail/PR-2717/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2717/detail/PR-2717/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-java_2717.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-07-19T16:06:04.931Z&rangeTo=2022-07-19T16:26:04.931Z&transactionName=BUILD+apm-agent-java%2Fapm-agent-java-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=6147e16c2711c09803c1345ebed8f934&transactionId=f77925c015f2378b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-19T16:16:04.931+0000


* Duration: 31 min 20 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 2381  |
| Skipped      | 22 |
| Total        | 2404   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2717/detail/PR-2717/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Builds / Tests / Non-Application Server integration tests / testLettuce[[io.lettuce:lettuce-core:5.0.5.RELEASE, io.netty:netty-all:4.1.28.Final]] – co.elastic.apm.agent.lettuce.Lettuce5VersionsIT`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 
Expecting value to be true but was false 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 org.opentest4j.AssertionFailedError: 

Expecting value to be true but was false
	at co.elastic.apm.agent.lettuce.Lettuce5VersionsIT.testLettuce(Lettuce5VersionsIT.java:50)
 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2717/detail/PR-2717/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Shell Script`
<ul>
<li>Took 15 min 58 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-java/pipelines/apm-agent-java-mbp/pipelines/PR-2717/runs/1/steps/336/log/?start=0">here</a></li>
<li>Description: <code>./mvnw -q -P ci-non-application-server-integration-tests verify</code></l1>
</ul>
  
  </p>
  </details>



## :bug: Flaky test report
:grey_exclamation: There are test failures but not known flaky tests.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run benchmark tests` : Run the benchmark tests.


- `run jdk compatibility tests` : Run the JDK Compatibility tests.


- `run integration tests` : Run the Agent Integration tests.


- `run end-to-end tests` : Run the APM-ITs.


- `run windows tests` : Build & tests on windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-20 08:50 UTC, eyalkoren requested changes
1. Transaction names is only one specific case of what's affecting the number of metricsets. The general factor that determine metricsets cardinality is the metrics labels (see `MetricRegistryTest`). So I propose talking about labels, but saying that it's better to reduce cardinality rather than increasing the limit is good, in which case you can mention transaction name as one option
2. You need to run `ConfigurationExporterTest` for this to be actually added to the documentation

2022-07-20 16:37 UTC, jackshirazi commented
Thanks @eyalkoren , is the latest version good enough, or still further changes needed?

2022-07-21 10:43 UTC, eyalkoren approved these changes

2022-07-21 12:35 UTC, merged